name = "yanyang-website-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[send_email]]
name = "EMAIL"

[vars]
REPO_OWNER = "Yanyang-Technology-Group"
REPO_NAME = "Yanyang_WebSite_date"
JWT_SECRET = "yanyang-backend-2026-secret"